In [115]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[1, 2, 3, 4, 5, 6, 7, 8]

In [127]:
i = -7
l[i:-2:2]

[3, 5, 7]

In [128]:
l += l

In [144]:
l

[0, 9, 0, 1, 2, 4, 5, 6, 7, 8, 9]

In [130]:
l.insert(1, 0.5)

In [149]:
print(l.__getitem__(slice(1,3)))
print(l[1:3])

[9, 0]
[9, 0]


In [156]:
import itertools

for ifi in zip(itertools.count(1), [1, 1, 2, 3, 5, 8]):
    print(ifi)

(1, 1)
(2, 1)
(3, 2)
(4, 3)
(5, 5)
(6, 8)


In [157]:
list(itertools.product(['a', 'b', 'c'], range(2)))

[('a', 0), ('a', 1), ('b', 0), ('b', 1), ('c', 0), ('c', 1)]

In [68]:
for c in itertools.combinations(['a', 'b', 'c', 'd'], 2):
    print(c)

('a', 'b')
('a', 'c')
('a', 'd')
('b', 'c')
('b', 'd')
('c', 'd')


In [158]:
import numpy

numpy.r_[0:2:0.5]

array([0. , 0.5, 1. , 1.5])

In [70]:
numpy.arange(0, 2, 0.5)

array([0. , 0.5, 1. , 1.5])

In [161]:
numpy.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [166]:
l = range(10)
i = iter(l)

In [170]:
print(next(i))
z = next(i)
print(z, next(i))
print(i.__next__())

StopIteration: 

In [175]:
class Fib6:
    def __init__(self):
        self.i = 0
        self.fibs = [1, 1, 2, 3, 5, 8]
    
    def __iter__(self):
        return self

    def __next__(self):
        if self.i >= 6:
            raise StopIteration()
        else:
            j = self.i
            self.i += 1
            return self.fibs[j]

In [173]:
f1 = Fib6()
for f in f1:
    print(f)
print(list(f1))

1
1
2
3
5
8
[]


In [176]:
f2 = Fib6()
f2i = iter(f2)
while True:
    try:
        print(next(f2i))
    except StopIteration:
        print("Done")
        break

1
1
2
3
5
8
/0


In [178]:
f3 = Fib6()
print(f3)
print(list(zip(
    itertools.count(1),
    itertools.islice(f3, 6)
)))

[(1, 1), (2, 1), (3, 2), (4, 3), (5, 5), (6, 8)]
